name: Deploy Python 3.9 App to OPC Server

on:
  push:
    branches:
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload project to remote server
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: opc
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: .
          target: /home/opc/python_app

      - name: Run deployment steps on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: opc
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/movie_meta

            # 使用虚拟环境（可选，但推荐）
            python3 -m venv venv
            source venv/bin/activate

            # 安装依赖
            pip install --upgrade pip
            pip install -r requirements.txt

            # 杀死旧进程（如果有）
            pkill -f app.py || true

            # 启动应用
            nohup venv/bin/python app.py > app.log 2>&1 &

            echo "✅ Python app deployed and started."
